/**
 * Hive — Global TypeScript Type Definitions
 *
 * Shared types used across client + server. Database-specific types
 * will be generated by Prisma in Phase 2 (@prisma/client).
 */

/* ─── User Roles ──────────────────────────────────────────────────── */
export type UserRole = "MEMBER" | "ORGANIZER" | "ADMIN";

/* ─── Community Score ─────────────────────────────────────────────── */
export type ScoreAction =
  | "ATTEND_EVENT"
  | "HOST_SESSION"
  | "VOLUNTEER"
  | "COMPLETE_PROFILE"
  | "REFER_MEMBER"
  | "HACKATHON"
  | "OPEN_SOURCE"
  | "PROJECT_SHOWCASE";

/* ─── Event Status ────────────────────────────────────────────────── */
export type EventStatus = "DRAFT" | "PUBLISHED" | "CANCELLED" | "COMPLETED";

/* ─── Registration Status ─────────────────────────────────────────── */
export type RegistrationStatus = "REGISTERED" | "WAITLISTED" | "CANCELLED";

/* ─── Attendance Status ───────────────────────────────────────────── */
export type AttendanceStatus = "PRESENT" | "ABSENT" | "LATE";

/* ─── Server Action Response ──────────────────────────────────────── */
export type ActionResult<T = void> =
  | { success: true; data: T; message?: string }
  | { success: false; error: string; fieldErrors?: Record<string, string[]> };

/* ─── Pagination ──────────────────────────────────────────────────── */
export interface PaginationParams {
  page: number;
  perPage: number;
}

export interface PaginatedResult<T> {
  data: T[];
  total: number;
  page: number;
  perPage: number;
  totalPages: number;
}

/* ─── Navigation ──────────────────────────────────────────────────── */
export interface NavItem {
  label: string;
  href: string;
  icon?: string;
  roles?: UserRole[];
  badge?: string;
}
